// Generated with Shader Minifier 1.3.6 (https://github.com/laurentlb/Shader_Minifier/)
#ifndef FRAG_DRAW_H_
# define FRAG_DRAW_H_
# define VAR_fragColor "f"
# define VAR_iFrame "v"
# define VAR_iResolution "m"

const char *draw_frag =
 "#version 430\n"
 "layout(location=0) out vec4 f;"
 "layout(location=0) uniform vec4 m;"
 "layout(location=1) uniform int v;"
 "const float a=acos(-1.);"
 "mat2 t(float v)"
 "{"
   "float a=cos(v),n=sin(v);"
   "return mat2(a,-n,n,a);"
 "}"
 "float n(vec3 v)"
 "{"
   "return(dot(abs(v),vec3(1))-1.5)/sqrt(3.);"
 "}"
 "float s(vec3 v)"
 "{"
   "float a=n(v);"
   "v.y=abs(v.y)-.15;"
   "return max(a,-n(v));"
 "}"
 "vec3 d(vec3 v)"
 "{"
   "return mod(v-4.,8.)-4.;"
 "}"
 "float e(vec3 v)"
 "{"
   "float a=1e9;"
   "for(int f=0;f<3;++f)"
     "a=min(a,s(d(v+vec3(4,0,4)))),a=min(a,s(d(v+vec3(0,4,0)))),v=v.yzx;"
   "return a;"
 "}"
 "float g;"
 "float d()"
 "{"
   "float v=fract(g++*.1031);"
   "v+=v*(v+19.19)*3.;"
   "return fract((v+v)*v);"
 "}"
 "vec2 e()"
 "{"
   "return vec2(d(),d());"
 "}"
 "void main()"
 "{"
   "g=float((v*73856093^int(gl_FragCoord.x)*19349663^int(gl_FragCoord.y)*83492791)%38069);"
   "vec2 d=(gl_FragCoord.xy+e()-.5)/m.xy-.5;"
   "d.x*=m.z;"
   "d*=4.+length(d);"
   "vec3 n=vec3(0,0,-10),r=normalize(vec3(d,1));"
   "vec2 z=(e()-.5)*t(a*.25);"
   "n.xy+=z*.5;"
   "r.xy-=z*.5/17.;"
   "n.yz*=t(atan(1.,sqrt(2.)));"
   "r.yz*=t(atan(1.,sqrt(2.)));"
   "n.xz*=t(a*.75);"
   "r.xz*=t(a*.75);"
   "vec3 l=vec3(.2*length(d),.1,.25);"
   "float y=0.,s=0.;"
   "for(int i=0;i<200;++i)"
     "{"
       "s=e(n+r*y);"
       "if(abs(s)<.001)"
         "break;"
       "y+=s;"
     "}"
   "if(abs(s)<.001)"
     "{"
       "vec3 i=n+r*y;"
       "vec2 u=vec2(.001,0);"
       "vec3 o=normalize(vec3(e(i+u.xyy),e(i+u.yxy),e(i+u.yyx))-s);"
       "float x=min(1.,pow(.9,y-20.));"
       "l=mix(l,vec3(dot(o,normalize(vec3(1,2,3)))*.35+.65),x);"
     "}"
   "f=vec4(l,1);"
 "}";

#endif // FRAG_DRAW_H_
