// Generated with Shader Minifier 1.3.6 (https://github.com/laurentlb/Shader_Minifier/)
#ifndef FRAG_DRAW_H_
# define FRAG_DRAW_H_
# define VAR_fragColor "f"
# define VAR_iFrame "m"
# define VAR_iResolution "v"

const char *draw_frag =
 "#version 430\n"
 "layout(location=0) out vec4 f;"
 "layout(location=0) uniform vec4 v;"
 "layout(location=1) uniform int m;"
 "const float i=acos(-1.);"
 "float r;"
 "float t()"
 "{"
   "float v=fract(r++*.1031);"
   "v+=v*(v+19.19)*3.;"
   "return fract((v+v)*v);"
 "}"
 "vec2 x()"
 "{"
   "return vec2(t(),t());"
 "}"
 "float t(vec2 v)"
 "{"
   "return fract(sin(dot(v,vec2(127.1,311.7)))*43758.5453);"
 "}"
 "float x(vec3 v)"
 "{"
   "return fract(sin(dot(v,vec3(127.1,311.7,74.7)))*43758.5453);"
 "}"
 "float n(vec2 v)"
 "{"
   "vec2 y=floor(v),f=fract(v);"
   "f=f*f*(3.-2.*f);"
   "return mix(mix(t(y),t(y+vec2(1,0)),f.x),mix(t(y+vec2(0,1)),t(y+vec2(1)),f.x),f.y);"
 "}"
 "float p(vec3 v)"
 "{"
   "vec3 y=floor(v),f=fract(v);"
   "f=f*f*(3.-2.*f);"
   "return mix(mix(mix(x(y),x(y+vec3(1,0,0)),f.x),mix(x(y+vec3(0,1,0)),x(y+vec3(1,1,0)),f.x),f.y),mix(mix(x(y+vec3(0,0,1)),x(y+vec3(1,0,1)),f.x),mix(x(y+vec3(0,1,1)),x(y+vec3(1)),f.x),f.y),f.z);"
 "}"
 "float h(vec2 v)"
 "{"
   "float y=0.,f=.5;"
   "for(int x=0;x<4;++x)"
     "y+=f*n(v),v=v*2.13+4.7,f*=.5;"
   "return y;"
 "}"
 "float e(vec3 v)"
 "{"
   "vec3 y=vec3(.46,.36,.46);"
   "float f=length(v/y);"
   "return f*(f-1.)/length(v/(y*y));"
 "}"
 "float e(vec3 v,vec3 f,vec3 m,float y,float x)"
 "{"
   "vec3 i=v-f,b=m-f;"
   "float e=clamp(dot(i,b)/dot(b,b),0.,1.);"
   "return length(i-b*e)-mix(y,x,e);"
 "}"
 "float e(float v,float f,float y)"
 "{"
   "float m=max(y-abs(v-f),0.)/y;"
   "return min(v,f)-m*m*y*.25;"
 "}"
 "vec2 e(vec2 f,vec2 v)"
 "{"
   "return f.x<v.x?"
     "f:"
     "v;"
 "}"
 "float s(float v)"
 "{"
   "return fract(sin(v*12.9898)*43758.5453);"
 "}"
 "vec2 w(vec3 v)"
 "{"
   "float y=e(v-vec3(0,.18,0));"
   "vec3 f=vec3(0,.46,0);"
   "float m=1e9;"
   "for(int x=0;x<16;++x)"
     "{"
       "float b=float(x),l=b*2.*i/float(16)+.1*s(b);"
       "vec3 n=vec3(cos(l),0,sin(l));"
       "float t=.22+.08*s(b+11.),c=.9+.18*s(b+37.),d=.04+.01*s(b+53.),w=-.04-.06*s(b+67.);"
       "vec3 r=f+n*.3*c+vec3(0,t*.65,0),C=r+n*.32*c+vec3(0,t*.2,0);"
       "float g=e(v,f,r,d,d*.85),D=e(v,r,C,d*.85,d*.55),F=e(v,C,C+n*.32*c+vec3(0,w,0),d*.55,d*.1),I=e(e(g,D,.06),F,.05);"
       "m=e(m,I,.04);"
     "}"
   "float l=e(y,m,.08);"
   "return vec2(l,m<y?"
     "3.:"
     "2.);"
 "}"
 "float u(vec2 v)"
 "{"
   "return.18*h(v*.7)+.04*h(v*4.5)-.06;"
 "}"
 "float l(vec3 v)"
 "{"
   "return(v.y-u(v.xz))*.55;"
 "}"
 "float d(vec3 v)"
 "{"
   "vec3 y=vec3(.75,.06,-.2);"
   "float f=(p((v-y)*14.)-.5)*.012;"
   "return(length((v-y)/vec3(.18,.12,.18))-1.)*min(.18,.12)*.75+f;"
 "}"
 "float c(vec2 v)"
 "{"
   "float f=.015*(sin(v.x*4.5+v.y*2.8)+sin(v.x*3.1-v.y*5.2));"
   "f+=.01*h(v*3.5);"
   "return f;"
 "}"
 "float g(vec3 v)"
 "{"
   "return(v.y-.2-c(v.xz))*.55;"
 "}"
 "vec2 o(vec3 v)"
 "{"
   "vec2 y=vec2(l(v),1),f=vec2(d(v),4),x=vec2(g(v),0);"
   "return e(e(e(y,f),w(v)),x);"
 "}"
 "vec2 a(vec3 v)"
 "{"
   "vec2 y=vec2(l(v),1),f=vec2(d(v),4);"
   "return e(e(y,f),w(v));"
 "}"
 "vec2 a(vec3 v,vec3 f,bool y)"
 "{"
   "float m=0.;"
   "vec2 i=vec2(1e9,-1);"
   "for(int x=0;x<96;++x)"
     "{"
       "vec3 l=v+f*m;"
       "i=y?"
         "o(l):"
         "a(l);"
       "if(abs(i.x)<.001||m>30.)"
         "break;"
       "m+=i.x;"
     "}"
   "return vec2(m,i.y);"
 "}"
 "vec3 a(vec3 v,bool y)"
 "{"
   "vec2 f=vec2(.001,0);"
   "return normalize(vec3((y?"
     "o(v+f.xyy).x:"
     "a(v+f.xyy).x)-(y?"
     "o(v-f.xyy).x:"
     "a(v-f.xyy).x),(y?"
     "o(v+f.yxy).x:"
     "a(v+f.yxy).x)-(y?"
     "o(v-f.yxy).x:"
     "a(v-f.yxy).x),(y?"
     "o(v+f.yyx).x:"
     "a(v+f.yyx).x)-(y?"
     "o(v-f.yyx).x:"
     "a(v-f.yyx).x)));"
 "}"
 "const vec3 y=normalize(vec3(-.75,.55,-.2)),b=vec3(1.05,.55,.22);"
 "vec3 C(vec3 v)"
 "{"
   "vec3 f=mix(vec3(.62,.32,.18),vec3(.06,.08,.15),clamp(v.y*1.2+.1,0.,1.));"
   "float m=max(0.,dot(v,y));"
   "f+=b*(pow(m,32.)*1.5+pow(m,4.)*.18);"
   "return f;"
 "}"
 "float C(vec3 v,vec3 y)"
 "{"
   "float f=1.,x=.02;"
   "for(int i=0;i<28;++i)"
     "{"
       "float m=a(v+y*x).x;"
       "if(m<8e-4)"
         "return 0.;"
       "f=min(f,10.*m/x);"
       "x+=clamp(m,.01,.25);"
       "if(x>4.)"
         "break;"
     "}"
   "return clamp(f,0.,1.);"
 "}"
 "float D(vec2 v)"
 "{"
   "float y=c(v),f=c(v+vec2(.03,0)),m=c(v-vec2(.03,0)),b=c(v+vec2(0,.03)),d=c(v-vec2(0,.03));"
   "return max(0.,(-f-m-b-d+4.*y)/9e-4*.6);"
 "}"
 "vec3 C(vec3 v,vec3 f,int m,vec3 x,bool i)"
 "{"
   "float d=dot(f,y),l=max(0.,d);"
   "vec3 r;"
   "float c=0.,e=32.,n=0.;"
   "if(m==1)"
     "{"
       "float t=h(v.xz*6.);"
       "r=mix(vec3(.2,.16,.13),vec3(.36,.3,.24),t);"
       "c=0.;"
     "}"
   "else if(m==2)"
     "r=mix(vec3(.42,.1,.13),vec3(.62,.18,.2),.5+.5*cos(atan(v.x,v.z)*10.)),c=.4,n=.2;"
   "else if(m==3)"
     "r=mix(vec3(.5,.13,.16),vec3(1.05,.55,.32),smoothstep(0.,1.,clamp(length(v.xz)*.95+(.46-v.y)*.6,0.,1.))),c=.6,n=.55;"
   "else if(m==4)"
     "{"
       "float t=p(v*6.);"
       "r=mix(vec3(.18,.16,.15),vec3(.3,.25,.21),t);"
       "c=i?"
         ".5:"
         ".25;"
       "e=48.;"
     "}"
   "else"
     " r=vec3(.5);"
   "float t=C(v+f*.002,y),s=i?"
     "D(v.xz)*t*(.4+.6*l):"
     "0.,w=n*pow(max(0.,-d)*.5+.5,2.)*t;"
   "vec3 g=r*(b*(l*t+w*.7)+vec3(.18,.28,.42)*(.5+.5*dot(f,vec3(0,1,0)))*.55)+b*s*.5;"
   "if(c>0.)"
     "{"
       "float u=pow(max(0.,dot(f,normalize(y-x))),e)*t*c;"
       "g+=b*u;"
     "}"
   "return g;"
 "}"
 "vec3 D(vec3 v,float y)"
 "{"
   "return mix(v*exp(-vec3(1.6,.7,.55)*y),vec3(.04,.1,.13),(1.-exp(-y*1.3))*.55);"
 "}"
 "void main()"
 "{"
   "r=float((m*73856093^int(gl_FragCoord.x)*19349663^int(gl_FragCoord.y)*83492791)%38069);"
   "vec2 i=(gl_FragCoord.xy+x()-.5)/v.xy-.5;"
   "i.x*=v.z;"
   "vec3 y=vec3(.25,.55,-1.9),l=vec3(.1,.32,.05),b=normalize(l-y),d=normalize(cross(b,vec3(0,1,0))),t=cross(d,b),n=normalize(b+i.x*d+i.y*t);"
   "vec2 e=x()-.5;"
   "e=(length(e)>.5?"
     "e/(2.*length(e)):"
     "e)*.045;"
   "vec3 g=y+d*e.x+t*e.y,s=normalize(y+n*length(l-y)-g);"
   "vec2 p=a(g,s,true);"
   "float u=p.x;"
   "int w=int(p.y+.5);"
   "vec3 F;"
   "if(u>=30.)"
     "F=C(s);"
   "else if(w==0)"
     "{"
       "vec3 I=g+s*u,z=a(I,true);"
       "if(dot(z,-s)<0.)"
         "z=-z;"
       "float o=clamp(-dot(s,z),0.,1.);"
       "vec3 h=reflect(s,z),k=C(h),A=refract(s,z,1./1.33),B;"
       "if(length(A)<.001)"
         "B=k;"
       "else"
         "{"
           "vec3 E=I+A*.002;"
           "vec2 G=a(E,A,false);"
           "if(G.x>=30.)"
             "B=vec3(.03,.08,.1);"
           "else"
             "{"
               "vec3 H=E+A*G.x,J=a(H,false);"
               "B=C(H,J,int(G.y+.5),A,true);"
               "B=D(B,G.x);"
             "}"
         "}"
       "F=mix(B,k,.02+.98*pow(1.-o,5.));"
     "}"
   "else"
     "{"
       "vec3 G=g+s*u,z=a(G,true);"
       "bool A=G.y<.2+c(G.xz);"
       "F=C(G,z,w,s,A);"
     "}"
   "f=vec4(F,1);"
 "}";

#endif // FRAG_DRAW_H_
